spring:
  kafka:
    bootstrap-servers: maprdemo:9092
  cloud:
    stream:
      bindings:
        output:
          contentType: application/*+avro
          destination: sensor-topic
      schema-registry-client:
        endpoint: http://localhost:3333
      schema:
        avro:
          schema-locations: classpath:avro/person.avsc
server.port: 5555